include(GNUInstallDirs)

set(CPACK_PACKAGE_NAME "auralis")
set(CPACK_PACKAGE_VENDOR "Auralis")
# No authoritative public contact in-tree yet — local builds remain functional.
# PUBLIC PACKAGE RELEASE METADATA: PENDING OWNER CONTACT
set(CPACK_PACKAGE_CONTACT "Auralis (contact pending)")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Multi-device Bluetooth and PipeWire audio hub")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${PROJECT_VERSION}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_GENERATOR "DEB")
set(CPACK_SOURCE_GENERATOR "")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Auralis (contact pending)")
set(CPACK_DEBIAN_PACKAGE_SECTION "sound")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)

include(CPack)
