option(AURALIS_BUILD_TESTS "Build Auralis tests" ON)
option(AURALIS_WARNINGS_AS_ERRORS "Treat compiler warnings as errors" OFF)
option(AURALIS_ENABLE_FILE_LOGGING "Enable file logging support" ON)
option(AURALIS_ENABLE_SANITIZERS "Build with AddressSanitizer and UndefinedBehaviorSanitizer" OFF)

if(AURALIS_ENABLE_SANITIZERS)
    if(MSVC)
        add_compile_options(/fsanitize=address)
        add_link_options(/fsanitize=address)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        add_compile_options(-fsanitize=address,undefined -fno-omit-frame-pointer)
        add_link_options(-fsanitize=address,undefined)
    else()
        message(FATAL_ERROR "AURALIS_ENABLE_SANITIZERS is not supported by this compiler")
    endif()
endif()
